pub mod file_manager;
pub mod companion;
pub mod gps;
mod wifi;
mod bluetooth;
mod cctv;
pub mod ssh;
pub mod display;
pub mod power;
mod radar;
mod joystick;
mod gesture;
mod voice_recognition;
mod thermal;
mod camera;
mod gsr;
mod heart_rate;
mod nfc;
mod mag_switch;
mod gas_sensor;
mod breadboard;
pub mod usb;